### ISSUE TITLE
Is there any way to add a new property to a widget using ChangeBuilder?

### ISSUE THREAD

**Issue by yasht01** [invertase/dart_custom_lint#102]
**Describe what scenario you think is uncovered by the existing examples/articles**
I want to add new property to a Text widget but the issue I am facing is some instances of the Text widget have a `,` after all the properties while some do not as shown below.
![image](https://user-images.githubusercontent.com/55907631/222681980-b0e251aa-fd38-43ea-b6ab-f64eb29dad5b.png)
![image](https://user-images.githubusercontent.com/55907631/222682048-d5bfba7e-796d-426b-9558-abcdd3eaede6.png)

I have been trying different methods of `ChangeBuilder` class and `InstanceCreationExpression` class to somehow get to know about that extra comma but with no luck.
Essentially, I want to somehow access if the widget contains an extra comma so that I can call the addSimpleInsertion method with an extra comma or not.

**Comment by rrousselGit** [comment]
Commas in the analyzer API are Tokens not AstNodes.

You can check `InstanceCreationExpression.argumentList.arguments.first.endToken` and possibly its `.next` property to possibly find it.
You should be able to obtain the commas this way.

**Comment by yasht01** [comment]
Thanks for the comment! This helped my issue 👍🏼
