### ISSUE TITLE
Allow running `custom_lint` in packages with different versions

### ISSUE THREAD

**Issue by alestiago** [invertase/dart_custom_lint#104]
**Describe the bug**

Currently running `flutter pub run custom_lint` will throw an error whenever a package A has a dependency on package B and C, and package B has also dependency on package C, but the versioning A has of C differs from the versioning B has of C.

I expect `custom_lint` to run where `dart analyze` runs.

**To Reproduce**

Since this issue requires a directory structure to reproduce, the minimal sample can be viewed [here](https://github.com/alestiago/issues/tree/dart_custom_lint-104-20230307).

The sample shows how a package can't be analysed since it has a developer dependency on `bloc 8.1.0` and its dependencies has a developer dependency on `bloc 8.1.1`

**Expected behavior**

`custom_lint` runs successfully where `dart analzye` runs successfully.

**Comment by alestiago** [comment]
I am aware that this is currently intended. 

I think this intention makes `custom_lint` unusable to run on "real" codebases if this is the case. Making it impossible to recommend as a tool.

**Comment by rrousselGit** [comment]
What you're asking isn't possible without major memory concerns.

You can run the command within one specific package instead of on the whole project at once. Then it'll work.

**Comment by alestiago** [comment]
Sorry, if the reply wasn't clear. I'll reformat it using your given format.

Given a project with the following architecture:
```
lib/
  foo.dart
packages/
  foo/
  bar/
pubspec.yaml
... # Other files
```

> To see a real example check [this](https://github.com/alestiago/issues/tree/dart_custom_lint-104-20230307/sample).

As you mentioned it might be possible to analyze `foo/` and `bar/`. What I'm saying is that it is impossible (due to the restriction) to analyse `foo.dart` without altering the versioning to align with its dependencies `foo/` and `bar/`. 

I hope this makes more sense, again thank you for the reply.

**Comment by rrousselGit** [comment]
There's a PR to allow `custom_lint lib` to analyze only the `lib` folder and exclude the `packages` one in your case.

But honestly, you probably should fix the error by aligning the versions.

**Comment by alestiago** [comment]
> I think this happens when you use path dependencies.

Indeed, the sample uses path dependencies and shows this issue. @kuhnroyal do you know if _git dependencies_ have the same issue?

With _git dependencies_ I mean dependencies in the form of:
```yaml
  foo:
    git: 
      url: https://github.com/alestiago/foo
      ref: bde6f320d6d278a82f40420df
```

**Comment by rrousselGit** [comment]
Path dependencies shouldn't impact this as long as all your projects use a path dependency.

**Comment by kuhnroyal** [comment]
> Path dependencies shouldn't impact this as long as all your projects use a path dependency.

Yea not in general, only when you have them as sub folders because they are detected as separate context roots and then leads to the conflict.

If it points to a different folder or if you use a git dependency, this should not be a problem.

**Comment by alestiago** [comment]
Awesome, thanks @kuhnroyal and @rrousselGit for participating in the conversation.

Given that it is not always possible to fix the error by aligning the versions. Do we all agree that this is a current issue with path dependencies?

**Comment by rrousselGit** [comment]
No as I said before, this is unrelated to path dependencies.

**Comment by alestiago** [comment]
Thanks @rrousselGit for the reply.

I agree with you. Ideally one would like the analyser to run on root and packages to visualise them within the IDE. In addition, in a utopian world, I also think that aligning the versions is also the simplest solution. However, in reality, is not always as easy to align the version of your root and packages folder, since this might be a tedious and complex process and it is not always possible to do so without compromises. 

So far, I think custom_lint is nailing the developer experience (in terms of writing the lint). However, I believe asking users of custom_lint (ie people using a lint rules made with custom_lint) to align the versions of their packages is a mayor drawback in terms of user experience. In some scenarios, this may lead to users being unable to use custom_lint at all, since the cost of aligning the versions might be greater than the benefit custom_lint brings to their codebases. In addition, Flutter developers are used to the dart analyser and I believe most would expect custom_lint to run without any complications (out of the box) just as the `dart analyze` does.

Out of curiosity, I would love to know why you think what I'm asking isn't possible without major memory concerns. If this is indeed impossible I think it should be communicated clearly as part of the documentation as a limitation of custom_lint so users decide if it's worth the cost using it. In addition, perhaps further improvements to the suggested command could be made since it doesn't always align the versions in all scenarios. An improvement could be, adding prompts (wizard) asking the user on what version they desire to stay with.

Contrary, if it is possible I would love custom_lint to have said functionality.

Anyways, let me know what do you think about the given suggestions and questions and how can we move forward to close the issue 💙 .

**Comment by rrousselGit** [comment]
There's a straightforward solution to your problem though: Don't open the whole project in your IDE at once.

As for the lib/packages issue, I'm suggest moving the root package inside the `packages` folder with the others. Then all of them will be in it, so opening a specific package won't open the other ones.
Alternatively your IDE should offer alternate ways to open the project without loading `packages` (cf folder exclude in vscode)

Custom_lint works by starting a single process that depends on all of the enabled plugins in your codebase. As such,
all plugins in your codebase must be compatible with each other.

The alternate solution is to have one process per pubspec.yaml with custom_lint enabled. But that means every project has to perform its own analysis. This can take gigabytes of memory per package with lots of it being duplicates (like the Flutter SDK being analyzed once per project).      
Hence why custom_lint uses a single process, to share that memory between all plugins instead of duplicating it.

That's the same reason why the `analysis_options.yaml` now allows only a single "plugin" listed:

```yaml
analyzer:
  plugins:
    - a
    # Not allowed anymore. Only a single plugin is allowed by Dart
    - b
```

There are improvements which could be made. Chances are there are a few cases where we could not throw. But fundamentally this restriction is likely here to stay.

It would help if you could explain more about your issue with the generated quick-fix though. Please make a new issue explaining your issues with it :)

**Comment by rrousselGit** [comment]
Honestly I'd like to avoid doing that. It's kind of dangerous to resolve dependencies to not use what's locally installed by analyzed apps.

**Comment by rrousselGit** [comment]
I'll close this in favour of the issues linked just above https://github.com/invertase/dart_custom_lint/issues/110 https://github.com/invertase/dart_custom_lint/issues/111
