### ISSUE TITLE
Flutter analyze command shows an error when custom_lint is enabled in a big project using a container

### ISSUE THREAD

**Issue by victorcatn** [invertase/dart_custom_lint#114]
When running `flutter analyze` with the `custom_lint` plugin enabled and the project is big, the command outputs:
```
Analyzing gallery...     
Error from the analysis server: Could not start the VM service: localhost:46297 is already in use.
Error from the analysis server: Failed to start plugins

...{normal analyzer errors}
```
Despite printing those errors the analyzer seems to execute correctly.

**To Reproduce**
Fork this repository and run the analyze workflow: [https://github.com/victorcatn/gallery/blob/customl2/.github/workflows/analyze.yml](https://github.com/victorcatn/gallery/blob/customl2/.github/workflows/analyze.yml)

**Expected behavior**
The analyze command doesn't output those two errors and shows only the normal problems.

I tried to reproduce the problem with a small project but the errors didn't pop. Maybe the analyzer must run for a while before the errors are shown.

**Comment by victorcatn** [comment]
[custom_lint: ^0.3.2](https://github.com/victorcatn/gallery/blob/c4906987af3455ed46a63ecc0789d7239b8d37d7/pubspec.yaml#L38)

**Comment by rrousselGit** [comment]
🤔 
In CI mode, it shouldn't even try to use vm-services. I'll look into it.

**Comment by Quijx** [comment]
Having the same problem btw, also using custom_lint: ^0.3.2
