### ISSUE TITLE
Incompatible with ffigen >=7.2.8

### ISSUE THREAD

**Issue by Yesterday17** [invertase/dart_custom_lint#130]
**Describe the bug**
```
Because ffigen >=7.2.8 depends on cli_util ^0.4.0 and every version of custom_lint depends on cli_util ^0.3.5,
  ffigen >=7.2.8 is incompatible with custom_lint.
```

**To Reproduce**

Add both ffigen and custom_lint in dev_dependency.

**Expected behavior**

Versioning should pass.

**Comment by rrousselGit** [comment]
Done in 31205a1fc7e4ff8985b1ca74c17cc3e8c4577bfa
