### ISSUE TITLE
Make the plugin work with multiple packages that share different dependencies' version

### ISSUE THREAD

**Issue by MaximeRougieux** [invertase/dart_custom_lint#143]
Disclaimer: I know this has already been discussed in https://github.com/invertase/dart_custom_lint/issues/104, and addressed partly by https://github.com/invertase/dart_custom_lint/pull/128, but I feel like the trade-off is still too painful to not do anything about it.

**Is your feature request related to a problem? Please describe.**
When working on medium to big size mono repo, the plugin won't start if some of the projects inside the mono repo have dependencies which resolves to different versions after a pub get.

**Describe the solution you'd like**
The plugin runs even if the resolved versions are not exactly the same.

**Describe alternatives you've considered**
In the `workspace.dart` file, instead of throwing if there are conflictual versions, the plugin could try to resolve each package to a single version by taking the minimum one for example. An example: If package A and package B depends on `meta` with resolved version `1.8.0` and `1.9.1`, the plugin would choose to keep the `1.8.0` instead of throwing.

I know there are other alternatives like opening each package separately when working on them, but I think this damages the devX too much. Aligning the versions isn't a good alternative either, because it would mean adding 'useless' lines to the `pubspec` of some packages (like a `meta:1.8.0` when the package actually has really an implicit `meta:^1.7.0` constraint which will almost always resolve to `1.9.1`.)

**Additional context**
I understand you didn't choose this path for a reason, but while testing it locally, I didn't run into any problem as long as the version gap is only between the minor/patch numbers (thank you semantic versioning). 
My understanding of the main dart analyzer is that it works similarly as what I describe, as it can run on some old flutter code even when using the latest analyzer version. I understand it can create inaccuracies when analyzing code which uses different versions of the analyzer's, but I think it's fine to have those inaccuracies and to work around them (and I prefer that rather than no analyzer at all).

Why did you pick this solution, is there something I don't see which prevents the plugin to work like this?

**Comment by rrousselGit** [comment]
> In the `workspace.dart` file, instead of throwing if there are conflictual versions, the plugin could try to resolve each package to a single version by taking the minimum one for example. An example: If package A and package B depends on `meta` with resolved version `1.8.0` and `1.9.1`, the plugin would choose to keep the `1.8.0` instead of throwing.

The behavior would be unreliable.

There's no telling whether the resulting code would compile or not with such an approach, and if it doesn't compile, the error would be extremely cryptic.  
This could also make it very difficult for plugin authors to debug possible problems if any. Running custom_lint on one specific project could have a different behavior than running it on a mono-repo since the dependencies picked-up could be different. That would be very confusing.

It's effectively the equivalent of praying to god that things will work out.  
That's not sane for the ecosystem.

**Comment by MaximeRougieux** [comment]
I understand, but isn't what the main dart analyzer does ?

**Comment by rrousselGit** [comment]
No it doesn't.

The analyzer doesn't rely on whatever package you have installed. It comes already fully pre-installed with the Dart SDK.  
It doesn't uses plugins. All lint rules provided by the analyzer are implemented within Dart itself and do not rely on anything from pub.dev.

So there's never a version conflict. 

Whereas with custom_lint that's the opposite. Who knows when starting the `custom_lint` command what the command will need to work? It has to dynamically load the source code of the various plugins you've installed in different projects, and make sure they are all compatible with each other.

**Comment by MaximeRougieux** [comment]
Thanks a lot for these explanations 🙏 

Do you tend to agree that it has a negative impact on the devX though? I'd love to help to find a solution to this, but if you don't see it as a problem, or if you think it's unsolvable with the current constraints of the analyzer, then I think we can close this issue.

What do you think?

**Comment by rrousselGit** [comment]
Of course it has a negative impact.

I'm just very careful about what we do here, because a badly designed solution could have dire consequences.  
For now the current solution is a bit inconvenient, but fairly safe.

**Comment by MaximeRougieux** [comment]
Sure, you're right to be cautious.

Thank you for taking the time to explain, the problem is easier to understand now. I have another question/solution idea if you don't mind.

Let's take a practical example with three packages, my_custom_lint, my_dart_package, and my_flutter_package.
Let's assume they have some dependencies but the only conflicting one is `meta`, as my_flutter_package is bound to use `meta:1.8.0`.

Here are the constraints:
```yaml
my_custom_lint:
  dependencies:
    meta: ^1.7.0 // resolved to 1.9.1

my_dart_package:
  dependencies:
    meta: ^1.7.0 // resolved to 1.9.1

  devDependencies:
    my_custom_lint:

my_flutter_package:
  dependencies:
    meta: 1.8.0 // resolved to 1.8.0

  devDependencies:
    my_custom_lint:
```
In this scenario, opening the three project in an IDE will make custom_lint throw because the resolved versions are different.

But actually there is a set of versions which make all those constraints work, right? If the custom_lint_client dependency to `meta` was resolved to `1.8.0`, it would match all the constraints. I'm not saying to take the lowest bound as before because that will create bugs, but trying to resolve the constraints a like what `pub get` does, would create a safe configuration for custom_lint which would work with more flexibility than the current setup, at least in my understanding.

Does it seem reasonable? Sorry if I miss some important points, my knowledge of the analyzer still is very light.

**Comment by rrousselGit** [comment]
This works, yes.
But as you might expect, there are many tricky situations.

Say you have:

```dart
# package A
dependencies:
   meta: ">=1.6.0 <1.9.0" # resolved with 1.7.0

# package B
dependencies:
   meta: ^1.8.0 # resolved with 1.9.0
```

Then even though the constraints are compatible, locally only 1.7.0 and 1.9.0 are available. But neither of them are compatible with both constraints at once. Only >=1.8.0<1.9.0 is, but we don't have a matching version for this. So it'll fail 



The algorithm for the package resolution would also likely be quite complex.

Maybe `pub get --offline` would work. Although I'm a bit skeptical about running it. It's both a bit slow to spawn a process for this and could possibly be confusing.   
If someone edits the source code of a dependency in the pub cache directory directly, they could be confused about why their changes aren't applied.

We'd also have to be very careful to make sure `dependency_overrides` are considered (and pubspec_overrides.yaml too).

And there's the possible concern of folks using third-party tools such as melos for resolving packages with a version different from what the `pubspec.yaml` mentions.  
If we run `pub get`, that would break those tools. Although melos 3.0 should be fine now as it relies on pubspec_overrides.



It's a bit tricky as you can see.

**Comment by alestiago** [comment]
Thanks, @MaximeRougieux for brining attention to this issue 💙 . I fully agree with:

> still too painful to not do anything about it

As a user of `custom_lint` I would be willing to use a less "safe" version if this painpoint is removed. Perhaps the CLI can have parameters to choose between the desire behaviour?

**Comment by rrousselGit** [comment]
Closing in favor of https://github.com/invertase/dart_custom_lint/issues/156.
