### ISSUE TITLE
Custom lint breaks when analysis_options.yaml is not at package root

### ISSUE THREAD

**Issue by Clavum** [invertase/dart_custom_lint#148]
If a package has additional `analysis_options.yaml` files that are not at the root of the package, then custom lint will attempt to read a `pubspec.yaml` at the same location as the analysis options. The pubspec doesn't exist, and custom lint fails to start. 

**Example**:
```
my_package
  lib
    ...
  test
    analysis_options.yaml
    ...
  analysis_options.yaml
  pubspec.yaml
```

Custom lint expects there to be a `pubspec.yaml` with every options file, and will throw the error:
`PathNotFoundException: Cannot open file, path = 'project/path/my_package/test/pubspec.yaml' (OS Error: No such file or directory, errno = 2)`

A PR was made to fix this several months ago, but was eventually abandoned.
https://github.com/invertase/dart_custom_lint/pull/19

**Comment by rrousselGit** [comment]
That's not the behavior I've seen. 
Do you mind making a quick github repository showcasing the problem, just so that we're on the same page?

I have multiple projects with a root analysis_options but no associated pubspec, and custom_lint works just fine on them.

**Comment by Clavum** [comment]
So I tried to make a minimal reproducible example, and yet for some reason it was not having the issue either. I kept trying to make it more similar to my package that isn't working (same Dart lints, structure, everything) but to no avail. I think the only difference between them at this point is the number of files/lines of code, and length of time they've existed...

Have any ideas what could cause it? I suppose when I get another chance to look into it I can clone and debug custom_lint myself.

**Comment by Clavum** [comment]
Looking into this a little bit right now.

For the package having issues, `allContextRoots` on line 178 of custom_lint/src/workspace.dart has two context roots, including the test folder.

For the package not having issues, `allContextRoots` has only a single context.

Seems pretty relevant to the issue. I'll continue to debug.

**Comment by TimWhiting** [comment]
I can confirm this breaks it.

**Comment by rrousselGit** [comment]
TIL that we can put `analysis_options.yaml`s inside the project instead of above it.Pretty sure I tried that before and it didn't work.

Fair enough then, this does need testing indeed

**Comment by Clavum** [comment]
@rrousselGit @TimWhiting Thanks for the progress made on the PR so far! It looks like it hasn't been touched for a few months now though. Is there any more progress being made? This seems like a significant issue because it entirely prevents the use of custom lint in some projects, which includes mine.

**Comment by TimWhiting** [comment]
Sorry, I've been out of the loop as far as this project goes. I'm unaware of what has changed as far as how custom_lint resolves packages since I last worked on the PR, but it looks like a lot has changed. Feel free to rebase the PR on the main branch and take over it if it is blocking you. I'm no longer actively working on it.

**Comment by mrgnhnt96** [comment]
@rrousselGit I think that this may have regressed lately, my nested analysis options files are not being respected anymore, I jumped from version `0.5.11` to `0.6.4`. Any idea what might have caused this?

**Comment by mrgnhnt96** [comment]
Actually, this is also happening with the `0.5.11` version as well. I did change flutter versions from 3.19.6 to 3.22.2. Perhaps there was a change in analyzer to make this act this way?
