### ISSUE TITLE
Add a way to retrieve all types of Comment node (not only documentation)

### ISSUE THREAD

**Issue by MattisBrizard** [invertase/dart_custom_lint#151]
Hi 👋 

I was looking for a way to add a `LintRule` on comments. I figured out that the `Comment` nodes retrieved with `LintRuleNodeRegistry.addComment` were only documentation comments. 
After investigating and opening [an issue](https://github.com/dart-lang/sdk/issues/52262) on the Dart repo, it seems that there is a wrong documentation of what a `Comment` node is.

I would like to have an easy way to retrieve all types of Comment in the `LintRule.run` method.

An other solution may be to use `StringScanner(source).tokenize` with the `String source` of the file retrieved with `resolver.source.contents.data`, but this would be better for users to have an easier way of retrieving all comments.

**Comment by rrousselGit** [comment]
:wave:

I'm not sure why this would be the responsibility of custom_lint. Could you expand on why something should be done here instead of in the analyzer package?

**Comment by MattisBrizard** [comment]
> The registry is a one-to-one match with GeneralizedAstVisitor though.
Yes that's what I saw. I was thinking of an extension method to not edit the `lint_visitor_generator`.

> Maybe if it picks up a lot of 👍 but for now I'd say no.
Ok with this. I let you decide if you want to close it.
