### ISSUE TITLE
Where can I find documentation about all of the registry methods?

### ISSUE THREAD

**Issue by dmrickey** [invertase/dart_custom_lint#162]
For example, I want to confirm that a certain method is never called. I can do something like this to manually check the name, but it seems like there's got to be a way to do it with all of the built in analyzers. But where do I go to find out which is the one that will give me what I'm looking for?
![image](https://github.com/invertase/dart_custom_lint/assets/3664822/546dabef-5db3-4375-a86f-4e07c2fe181a)

**Comment by rrousselGit** [comment]
There's one method per Analyzer object. I'm not the one who defines what the analyzer objects are. It's the analyzer package which does it. The registry is only an interface for easy/efficient access.

You'll have to learn a bit of analyzer to know which object you care about. It's not really custom_lint's responsibility to document every analyzer object.

I'd suggest playing around until you find what you're looking for

**Comment by dmrickey** [comment]
I can understand not being responsible for documenting types coming out of another package. But for an integral part of this package, a simple link _somewhere_ that says where the documentation for "Analyzer" types is expected instead of not being able to find any mention of it

**Comment by rrousselGit** [comment]
There's no such link though. The closest you'll have is stepping in the source of analyzer or the autocompletion on custom_lint's registry or things like AstVistor
