### ISSUE TITLE
Ability to ignore single rules

### ISSUE THREAD

**Issue by bw-flagship** [invertase/dart_custom_lint#169]
**Is your feature request related to a problem? Please describe.**
We use a custom lint package in our company across projects. There are some lints with 90% of the projects like, but it would be a non-fit for the other 10%. Currently, they have to either accept all or none.

**Describe the solution you'd like**
I would appreciate it if we could disable single rules in the analysis options.yaml, e.g.

```yaml
linter:
  rules:
    - shorten_repository_name: false
```

Shorten_repository_name is my custom rule.

**Describe alternatives you've considered**
An alternative solution is to use //ignore very often, but this is error-prone and not smooth.

**Comment by rrousselGit** [comment]
This is supported. Although I'm surprised this isn't in the readme.

The syntax is:

```dart
custom_lint:
  rules:
     - your_rule: false
```

**Comment by rrousselGit** [comment]
I've added it to the README
