### ISSUE TITLE
Dependency on riverpod 2.0.0-dev.9

### ISSUE THREAD

**Issue by MarcinusX** [invertase/dart_custom_lint#17]
`custom_lint 0.0.9+1` depends on `riverpod 2.0.0-dev.9` meaning we cannot using while using stable `riverpod 1.0.3`.
Is there something that can be done about it besides switching to dev version of Riverpod?

**Comment by rrousselGit** [comment]
Consider using 2.0

It's going to be stable by September.

**Comment by MarcinusX** [comment]
I know it's not riverpod repo but are there any known issues preventing considering using 2.0 as stable?

**Comment by rrousselGit** [comment]
There are more features to come for the 2.0

**Comment by TimWhiting** [comment]
I've been using riverpod 2.0 fine for awhile now, riverpod's dev releases tend to be very stable because of the thorough tests, additionally the advantage is that you get to migrate feature by feature as they come out rather than all at once.

**Comment by Salakar** [comment]
Closing as latest release now uses stable riverpod 2.0.0
