### ISSUE TITLE
Reference Rename

### ISSUE THREAD

**Issue by 0xNF** [invertase/dart_custom_lint#179]
Is there a way to rename references across the codebase? I have a lint that can fix certain method names, but then I just invalidate all previous references to the object in question.

**Comment by rrousselGit** [comment]
There is no such thing at the moment. To begin with, we don't quite know about all references of a symbol in the project.

Some files aren't necessarily analyzed yet for instance.

**Comment by 0xNF** [comment]
This is a related question, so I don't want to open a second issue for it:

Will this project at some point be able to look at the source of a symbol? This almost certainly depends on the same ability to load all symbol references, but it'd be really nice to make lints conditional on elements of a symbol defined outside the specific file being examined.

**Comment by 0xNF** [comment]
I want to inspect symbols for the presence of custom @annotations on their definition and make lints based on their presence or absence.

I also want to look at functions that return values, but whose return values are never assigned. In both cases, I need to be able to check an invocation or a field. I think this might be out of scope for a linter, and might be more line with an actual analyzer / LSP.

**Comment by rrousselGit** [comment]
You already have that information. While Ast is specific to the current file, "Elements" aren't.

You could do:

```dart
VariableDeclaration node;
final element = node.declaredElement?.type.element; // The element of the variable type
if (element is InterfaceElement) {
  // If the type is a class

  print('The variable has the following methods:');
  element.methods.forEach((method) {
    print(method.name);
  });
}
```

**Comment by 0xNF** [comment]
Oh, that's quite useful. That makes way more things possible. Thanks for pointing that out.  I'll mark this closed for now, I think I can get most of what I want out of the current features.
