### ISSUE TITLE
Accessing `nameLintLocation` of import statements returns `null`

### ISSUE THREAD

**Issue by Marceeelll** [invertase/dart_custom_lint#18]
### Goal
A custom lint rule that checks the import statements of a given file.

### Code Snipped
```Dart
Stream<Lint> getLints(ResolvedUnitResult unit) async* {
    final imports = unit.libraryElement.imports;
    final import = imports.first;
    ...
    yield Lint(
        severity: LintSeverity.error,
        code: 'code',
        message: 'message',
        correction: 'correction',
        location: import.nameLintLocation,
    );
}
```
### Expected
To access the `import.nameLintLocation` property to yield a lint at a given location of the import statement.

### Result
`import.nameLintLocation` returns `null`

**Comment by rrousselGit** [comment]
That's expected. Imports don't have a name.

**Comment by rrousselGit** [comment]
Closing as this is expected. If you want the location of an import statement, you likely would have to find its "AstNode".
