### ISSUE TITLE
no UI in android studio

### ISSUE THREAD

**Issue by mhdjazmati** [invertase/dart_custom_lint#191]
**Describe the bug**
on console it runs
but no ui in android studio
Android Studio Chipmunk | 2021.2.1 Patch 2
Build #AI-212.5712.43.2112.8815526, built on July 10, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64
**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**

**Comment by rrousselGit** [comment]
Make sure that you enabled custom_lint in your analysis_options.yaml
The command line can work without this step, but not the IDE.

Could you double check in VScode that you do see the lints?

Also check your custom_lint.log to verify that there isn't a error

**Comment by Linkadi98** [comment]
I have similar problem, in VSCode everything works fine but in Android Studio, no lint error messages show up. The logs say: 
<img width="1086" alt="image" src="https://github.com/user-attachments/assets/c5e85da6-1e1c-4b04-9ecc-4d1848965421"> @rrousselGit

**Comment by Linkadi98** [comment]
VSCode lint: 
<img width="793" alt="image" src="https://github.com/user-attachments/assets/a25315af-f597-421b-8b5f-04aa36eb568f">
Android Studio no lint message: 
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/5b6688bd-047e-4c56-95f1-7793a65d956d">

**Comment by jogboms** [comment]
I also now experience this

**Comment by karabanovbs** [comment]
I had the same problem, i dont know why, but Android studio [can't create tmp folder](https://github.com/invertase/dart_custom_lint/blob/main/packages/custom_lint/lib/src/v2/server_to_client_channel.dart#L147). 
I was try run Android Studio with sudo and it helps me.

**Comment by JoseAlba** [comment]
Yeah, I got the same issue as everyone else. I tried running Android Studio in sudo mode but the issue persisted.

**Comment by rrousselGit** [comment]
The issue should be gone once you upgrade to the latest

**Comment by MartinAKovachev** [comment]
Seems like the issue still persists in IntelliJ and Android Studio.

**Comment by AhmedEzio47** [comment]
@rrousselGit Could you please specify the version where this issue is fixed? Because I'm on version 8.0.0 and  I still face it.
