### ISSUE TITLE
Support git dependency for plugins

### ISSUE THREAD

**Issue by johannessachse** [invertase/dart_custom_lint#20]
I created a lint_package and tried to use this package within my application:

### 1. Project structure
**lint_package structure**
pubspec.yaml
```
dependencies:
  analyzer: ^4.2.0
  analyzer_plugin: ^0.10.0
  custom_lint_builder: ^0.0.9+1
```
In my custom_lint file (`bin/custom_lint.dart`) I have several imports:
```
import 'dart:isolate';

import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:analyzer/source/source_range.dart';
import 'package:analyzer_plugin/protocol/protocol_generated.dart';
import 'package:analyzer_plugin/utilities/change_builder/change_builder_core.dart';
import 'package:custom_lint_builder/custom_lint_builder.dart';
```

**application structure**
pubspec.yaml
```
dependencies:
  custom_lint:
  lint_package:
     git:
        url: [...]
        ref: [...]
```
analysis_options.yaml
```
analyzer:
  plugins:
    - custom_lint
 ```

### 2. Problem
When running `flutter pub get` or `dart run custom_lint` within my application I get the following error:
```
IsolateSpawnException: Unable to spawn isolate: Error: Error when reading '**/.pub_cache/**/lint_package/.dart_tool/package_config.json': No such file or directory
Error: Couldn't resolve the package 'analyzer' in 'package:analyzer/dart/analysis/results.dart'.
Error: Couldn't resolve the package 'analyzer' in 'package:analyzer/dart/ast/ast.dart'.
Error: Couldn't resolve the package 'analyzer' in 'package:analyzer/dart/element/type.dart'.
Error: Couldn't resolve the package 'analyzer' in 'package:analyzer/source/source_range.dart'.
Error: Couldn't resolve the package 'analyzer_plugin' in 'package:analyzer_plugin/protocol/protocol_generated.dart'.
Error: Couldn't resolve the package 'analyzer_plugin' in 'package:analyzer_plugin/utilities/change_builder/change_builder_core.dart'.
Error: Couldn't resolve the package 'custom_lint_builder' in 'package:custom_lint_builder/custom_lint_builder.dart'.
```

The `.dart_tool` directory is not included in my lint_package repository.

If I manually execute `flutter pub get` in my local copy of this package (`.pub-cache/**/lint_package`) everything works as expected.

**Comment by vs-krasnov** [comment]
It is possible to push the `.dart_tool` directory to the git repo. 
In this case, the package is fully operational within the app.

However, this workaround is not possible for packages hosted at the pub.dev.
We've deployed our [custom lints package](https://pub.dev/packages/supernova_lints#missing_this) and it throws the same exception regarding missing `package_config.json`.
The thing is it is not possible to include `dart_tool` in the published package, the folder is just filtered out 😞

**Comment by rrousselGit** [comment]
I'll look into it tomorrow to see if there's a quick fix (like running `pub get` in the project). But if not, it'll probably have to wait a bit

**Comment by rrousselGit** [comment]
I'll look into it tomorrow to see if there's a quick fix (like running `pub get` in the project). But if not, it'll probably have to wait a bit

**Comment by irufano** [comment]
I got same issue

**Comment by rrousselGit** [comment]
I'm done with the Flutter Vikings. So I'll look into this issue asap
