### ISSUE TITLE
Access pubspe's dependencies in PluginBase.getLintRules

### ISSUE THREAD

**Issue by charlescyt** [invertase/dart_custom_lint#200]
Hello!

I am trying to disable a lint if it is a pure dart project. Right now I am doing the check inside `DartLintRule.run`. Would it be possible to move the checking into `PluginBase.getLintRules`?

```dart
void run(
  CustomLintResolver resolver,
  ErrorReporter reporter,
  CustomLintContext context,
) {
  final dependencies = context.pubspec.dependencies;
  if (!dependencies.containsKey('flutter')) return;
}
```

to

```dart
List<LintRule> getLintRules(CustomLintConfigs configs, Pubspec pubspec) => [
  if(isFlutterProject)
    ...flutterLintRules,
  if(isRiverpodInstalled)
    ...riverpodLintRules,
];
```

**Comment by rrousselGit** [comment]
That is not possible. `getLintRules` is called on an entire workspace, not on a per-project basis.
Projects can be added/removed to the workspace, or their pubspec.yamls can be edited at any time. But the list of lint rules does not change.

At the same time, there are plans to have a command for listing all possible lint rules available.

**Comment by charlescyt** [comment]
I see. Is putting the checking logic inside `run` the recommended way?
Another approach that I can think of is to separate the package into a flutter and dart one.

**Comment by rrousselGit** [comment]
Putting the logic in `run` is fine. That'd generally how I do it.

**Comment by charlescyt** [comment]
Thanks for your help!
