### ISSUE TITLE
Ignore comment is not properly indented

### ISSUE THREAD

**Issue by PiotrRogulski** [invertase/dart_custom_lint#206]
**Describe the bug**
When ignoring a custom lint creates a new `// ignore: ...` comment (i.e., it's the first ignore for the line), the comment is always created at column 0 instead of being aligned with non-whitespace content.

**To Reproduce**

Create code that triggers a custom lint at a non-zero column, then ignore this lint. A sample can be found in this repo: [PiotrRogulski/custom_lint_indent](https://github.com/PiotrRogulski/custom_lint_indent/blob/main/bin/custom_lint_indent.dart).

**Expected behavior**
The ignore comment is aligned so that it begins in the same column as the first non-whitespace character of the target line. This is the behavior of built-in lints.

This is caused by the `custom_lint_builder` package, which inserts the comment always at the beginning of the line — [file `lib/src/ignore.dart`, lines 126–134](https://github.com/invertase/dart_custom_lint/blob/bb816118221bf016cdf0094b8a20492eeaa519bb/packages/custom_lint_builder/lib/src/ignore.dart#L126).

| Expected | Actual |
|----------|--------|
| ![expected](https://github.com/invertase/dart_custom_lint/assets/18120733/ac28fb7b-b75b-4cd6-9f27-0f344c4db413) | ![actual](https://github.com/invertase/dart_custom_lint/assets/18120733/a9218af0-fba1-40e3-9bd0-48afd9d9c374) |

**Comment by rrousselGit** [comment]
It's easier this way and low priority for me

**Comment by PiotrRogulski** [comment]
I created the fix for this locally; if it's OK I would be happy to open a PR for this

**Comment by rrousselGit** [comment]
Sure go ahead
