### ISSUE TITLE
Negate `// expect_lint: LINT_NAME` for testing

### ISSUE THREAD

**Issue by mrgnhnt96** [invertase/dart_custom_lint#209]
As a developer, I would like to test the custom lints for when a lint _is expected_ as well as when a lint _is_ **not** _expected_.

**Describe the solution you'd like**
The end goal would be to negate the expectation of a lint that is being tested.

```dart
// We are expecting the lint to be here
// expect_lint:  use_pascal_case
class bad_casing {}

// We are NOT expecting the lint to be here
// expect_lint: no:use_pascal_case
class GoodCasing {}

// Alternative Solutions
// expect_no_lint: use_pascal_case
// expect_lint: !use_pascal_case
// expect_lint: NOT:use_pascal_case
```

**Comment by rrousselGit** [comment]
You don't need a comment for this.  
If your lint emits a lint, then you will have analysis issues, causing `custom_lint` to fail.

**Comment by mrgnhnt96** [comment]
Ah yeah, well I guess that's true. I was looking for a more explicit way for testing, but this will work. Thanks Remi!
