### ISSUE TITLE
`// expect_lint` doesn't work when error's offset starts at 0

### ISSUE THREAD

**Issue by mrgnhnt96** [invertase/dart_custom_lint#210]
**Describe the bug**
I am creating a lint for filename formatting. I have set the report error for node to be the entire file

```dart
    // "run" method
    ...

    final result = await resolver.getResolvedUnitResult();

    ...
    
    reporter.reportErrorForNode(
      _code,
      result.unit,
    );
```

When I test the lint, I get the lint warning saying that the file is not correct as well as an error that says that the lint is not found.

<img width="1002" alt="image" src="https://github.com/invertase/dart_custom_lint/assets/39742020/9f2e453a-0bb1-4f44-92bd-0b5ebbc8ec76">

**To Reproduce**

- Add the Zero Offset lint to a new custom_lint project.
- Create any file for testing
- Add `// expect_lint: offset_zero` to the first line of the test file
- View the lint warning of the zero offset and lint error of the missing lint

```dart
import 'package:analyzer/error/listener.dart';
import 'package:custom_lint_builder/custom_lint_builder.dart';

class Lint extends DartLintRule {
  const Lint() : super(code: _code);

  static const _code = LintCode(
    name: 'offset_zero',
    problemMessage: 'The offset is zero.',
  );

  @override
  Future<void> run(
    CustomLintResolver resolver,
    ErrorReporter reporter,
    CustomLintContext context,
  ) async {
    final result = await resolver.getResolvedUnitResult();

    reporter.reportErrorForOffset(_code, 0, 0);
  }
}
```

**Expected behavior**
I would expect the lint to be able to check for same line lint warnings

**Comment by rrousselGit** [comment]
That's to be expected. The same thing would happen with `// ignore: code`

Warning at offset 0 in a file is not a very reliable pattern. It's generally better to warn on the first thing found in a file instead (imports, library directives, ...)

**Comment by mrgnhnt96** [comment]
I don't think this is actually expected.

The reason that this fails is because when the check between the locations of the lint and the expect lint are compared, the expect lint's location is -1, because of the index offset of 1 then minus 1 to get the location of the lint. Technically -1 shouldn't ever happen since we can't have -1 characters in a file.

I'm in the middle of working on a fix for this. I should have something ready by tomorrow, I was running the tests to make sure everything passed before my day ended.

The reason that there needs to be a fix is because if the starting point of the lint is actually 0 then extends to the end of the file (regardless of length) the expect lint can never be resolved because -1 != 0.

**Comment by mrgnhnt96** [comment]
If anyone else comes here with this question.. Instead of setting the offset to 0, the solution is to get the offset of the first line and providing that to the reporter. This can be achieve with 

```dart
final offset = result.unit.lineInfo.getOffsetOfLine(1);
```

Then the `expect_lint` works as expected.

![image](https://github.com/invertase/dart_custom_lint/assets/39742020/f22ac692-9fe8-4814-9368-fe0c7b5c83cb)

**Comment by rrousselGit** [comment]
Note that an enhancement alternative could be to support placing `// expect_lint` in the same line as the problematic lint.

Like:

```dart
someCodeThatWarns; // expect_lint: my_lint
```
