### ISSUE TITLE
context.registry.addComment is only triggered by documentation comments

### ISSUE THREAD

**Issue by Mathorga** [invertase/dart_custom_lint#211]
**Describe the bug**
When defining a new DartLintRule, the context.registry.addComment callback is only triggered for documentation comments (single line starting with "///") and not for end-of-line (single line starting with "//") and block (surrounded by "/*  */") comments.

**To Reproduce**
Here I'm trying to report and error for comment nodes which contain the "TOCHECK" string:
```
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/token.dart';
import 'package:analyzer/error/error.dart';
import 'package:analyzer/error/listener.dart';
import 'package:custom_lint_builder/custom_lint_builder.dart';

class TocheckComments extends DartLintRule {
  static const LintCode _code = LintCode(
    name: "tocheck_comments",
    problemMessage: "Remember to check this",
    errorSeverity: ErrorSeverity.INFO,
  );

  TocheckComments() : super(code: _code);

  @override
  void run(
    CustomLintResolver resolver,
    ErrorReporter reporter,
    CustomLintContext context,
  ) {
    context.registry.addComment((Comment node) {
      if (node.tokens.any((Token token) => token.toString().contains("TOCHECK"))) {
        reporter.reportErrorForNode(_code, node);
      }
    });
  }
}
```

Behavior with doc comment:
![image](https://github.com/invertase/dart_custom_lint/assets/32356959/4c1c8118-518a-436c-9b39-be446d0ec74f)

Behavior with eol comment:
![image](https://github.com/invertase/dart_custom_lint/assets/32356959/9d206933-d07f-43a8-ae1a-c638a1ea21df)

Behavior with block comment:
![image](https://github.com/invertase/dart_custom_lint/assets/32356959/65154506-f668-48e9-8728-5dee4896c582)

I'm currently using Flutter 3.16.5, VSCode 1.85.1, Windows 11

**Expected behavior**
I would expect the lint rule to be triggered by non-doc comments as well as for doc comments.

**Comment by rrousselGit** [comment]
custom_lint isn't responsible for this. It's only giving you what the analyzer gives us, under a different format.

If you want Comment instances in those situations, you should ask in https://github.com/dart-lang/sdk for it

**Comment by Mathorga** [comment]
Alright then, my bad, heading to dart-lang,
thank you
