### ISSUE TITLE
I have created a Flutter application which can run on iOS and android. I want to convert it as package which can be installed in other flutter apps. 

### ISSUE THREAD

**Issue by komalkhatri08** [invertase/dart_custom_lint#215]
I have created a Flutter application which can run on iOS and android. 
I want to **convert it into a package which can be installed in other flutter apps.**

my Flutter app is a basic framework app with integrated push notification feature using azure notification hub, TDD, remote logging, azure service bus connection, use of graphQL and sending event to EventGrid in Azure.  etc.... 

I want this framework to be downloaded with single command in another flutter projects. is it possible?

**Comment by rrousselGit** [comment]
Hello!
How is this related to custom_lint?

**Comment by komalkhatri08** [comment]
Oh, I am sorry i raised at wrong place. Thanks to le me know.

**Comment by komalkhatri08** [comment]
Raised the issue in wrong forum. Sorry for inconvenience
