### ISSUE TITLE
Custom lint command to be executed via Azure Devops pipeline

### ISSUE THREAD

**Issue by vai309** [invertase/dart_custom_lint#219]
Is it possible to run custom lint check while implementing Azure devops pipeline? 
My app is created in Flutter and I am able to run Flutter Analyzer in azure devops pipeline .
tried using this command :- **dart pub global run custom_lint**
it shows error that dart is not available in Azure pipeline. Si there any other way ?

Thanks.

**Comment by rrousselGit** [comment]
This isn't a custom_lint issue. You first need to instal Dart in your Azure pipeline. I'd suggest googling on how to do that :)
