### ISSUE TITLE
Documentation on testing quick fixes and assists

### ISSUE THREAD

**Issue by charlescyt** [invertase/dart_custom_lint#220]
**Describe what scenario you think is uncovered by the existing examples/articles**

Currently, the documentation only mentions testing lints with `// expect_lint: `. I believe it is also important to test quick fixes and assists.

Would it be possible to add a brief introduction on testing quick fixes and assists to the docs?

**Comment by rrousselGit** [comment]
You could look at how Riverpod does it for reference: https://github.com/rrousselGit/riverpod/tree/master/packages/riverpod_lint_flutter_test/test/assists

TL;DR, it uses normal tests, combined with `pkg:analyzer` to manually execute the assists/fixes

**Comment by charlescyt** [comment]
Thanks for the reply. Shall we add this information in the documentation? People using custom lint are not necessarily aware of Riverpod.
