### ISSUE TITLE
Analysis Never Completes When `custom_lint` Plugin Added to `analysis_options.yaml`

### ISSUE THREAD

**Issue by ykaito21** [invertase/dart_custom_lint#226]
### Environment
- **Visual Studio Code Version**: 1.86.1
- **Dart Plugin Version**: v3.83.20240207
- **Flutter Plugin Version**: v3.83.20240201 
- **Flutter SDK Version**: Channel stable, 3.16.9

### Description
After adding the `custom_lint` plugin to my `analysis_options.yaml` and including the plugin in my `pubspec.yaml`, the Dart analyzer in Visual Studio Code never completes. This issue occurs even without making any code changes after initializing a new Flutter project with `flutter create`. Removing the `custom_lint` plugin resolves the issue, suggesting that the problem is specifically related to the interaction between the Dart analyzer and the `custom_lint` plugin in Visual Studio Code.

### Steps to Reproduce
1. Create a new Flutter project with `flutter create`.
2. Add `custom_lint: ^[version]` to the `dev_dependencies` section of `pubspec.yaml`.
3. Add the following to `analysis_options.yaml`:
   ```yaml
   analyzer:
     plugins:
       - custom_lint
   ```
4. Open the project in Visual Studio Code.
5. Observe that the Dart analysis never completes.

### Expected Behavior
The Dart analyzer should complete its analysis of the project, including when the `custom_lint` plugin is added.

### Actual Behavior
The Dart analyzer gets stuck and never completes its analysis when the `custom_lint` plugin is included.

### Additional Information
- The issue persists even after restarting Visual Studio Code and reloading the project window.
- Running `flutter analyze` from the command line completes without issues, suggesting that the problem is specific to Visual Studio Code.
- No relevant output or error messages are visible in the Dart and Flutter extension logs in the Output panel of VS Code.

### Doctor Result
```
[✓] Flutter (Channel stable, 3.16.9, on macOS 13.4 22F66 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.86.1)
[✓] Network resources
```

This issue is also tracked in https://github.com/dart-lang/sdk/issues/54883#issue-2129749565

I suspect there may be a compatibility issue or a bug related to the `custom_lint` plugin's interaction with the Dart analyzer in Visual Studio Code. Any insights or assistance in resolving this problem would be greatly appreciated.

**Comment by rrousselGit** [comment]
I don't have the issue. It's likely something specific to your environment.

Could you share a minimal reproducible example? Like a project to clone with custom_lint installed where the issue triggers.

**Comment by ykaito21** [comment]
Thank you for your feedback. It's quite possible that the issue I'm encountering is unique to my environment, as it appears others are not experiencing the same problem. My local setup might be influencing the behavior of the Dart analyzer in conjunction with the `custom_lint` plugin.

I've created a GitHub repository that encapsulates the setup required to trigger the issue I've been facing. https://github.com/ykaito21/flutter_analysis_issue
Any insights or suggestions based on this repository would be greatly appreciated.

**Comment by rrousselGit** [comment]
I have no issue personally.

Now, you haven't added any custom_lint plugin, so custom_lint isn't doing much. But analyzer is working fine

**Comment by ykaito21** [comment]
Thank you for taking the time to look into the repository and for your observations. Indeed, as you pointed out, I have not added the `custom_lint` plugin into the project yet, but even when I proceed with adding specific lint rules, such as those provided by riverpod_lint, I encounter the same issue. 

The problem could be my local development environment. Thanks for your help!

**Comment by rrousselGit** [comment]
It's a bit difficult for me to help you here then.

Do you have a custom_lint.log file that appears at least?

**Comment by ykaito21** [comment]
I completely uninstalled VSCode including all extensions and settings and reinstalled from scratch. The problem seems to be resolved.

Thank you so much for taking the time to help me.

**Comment by famasf1** [comment]
> I completely uninstalled VSCode including all extensions and settings and reinstalled from scratch. The problem seems to be resolved. I don't know why, but in my case the problem occurred with `"dart.onlyAnalyzeProjectsWithOpenFiles": true`.
> 
> Thank you so much for taking the time to help me.

Turning `dart.onlyAnalyzeProjectsWithOpenFiles` off and reinstalling VSCode also solved mine as well. Absolutely bizarre.
