### ISSUE TITLE
Failures resolving packages with pub get on Windows

### ISSUE THREAD

**Issue by srtonz** [invertase/dart_custom_lint#237]
**Describe the bug**
On Windows, when custom_lint goes into the `catch` block below and calls `runPubGet`, two issues occur:

https://github.com/invertase/dart_custom_lint/blob/6d4425e17033e76fd85787372f2c8db9c218828f/packages/custom_lint/lib/src/workspace.dart#L805-L809

1. Calling `Process.run` ([here](https://github.com/invertase/dart_custom_lint/blob/6d4425e17033e76fd85787372f2c8db9c218828f/packages/custom_lint/lib/src/workspace.dart#L833C20-L833C26)) fails, because no absolute path to the `pub` executable is provided. Even with `pub` in the system PATH, Windows will be unable to find the executable. From the Dart docs:
    > Using an absolute path for executable is recommended since resolving the executable path is platform-specific. On Windows, both any PATH set in the environment map parameter and the path set in workingDirectory parameter are ignored for the purposes of resolving the executable path.

2. When the project uses local dependencies (specified through `path` in pubspec), the generated pubspec.yaml uses Windows-style path separators (`\`), which are then treated as escape characters by pub:
    ```
    Error on line 12, column 14: Unknown escape character.
       ╷
    12 │     path: "C:\git\mypackage\packages\my_lints"
       │              ^
       ╵
    ```

**To Reproduce**
Force the package to call `runPubGet` on Windows.

**Expected behavior**
I'd expect the package to either throw a useful exception on Windows or somehow handle this case.

**Fixes**
  1. The first issue can be fixed by adding `runInShell: true` as an argument to `runProcess`, or better `runInShell: Platform.isWindows` to avoid spawning a new shell on other platforms.
    A possible problem with that approach is that it will always use the Dart installation found in the system PATH. I'm not 100% sure how it'll play with tools such as fvm, but I think the current implementation has the same "problem".

  2. For the second issue, I think we can convert Windows-style to Posix-style path separators here: https://github.com/invertase/dart_custom_lint/blob/6d4425e17033e76fd85787372f2c8db9c218828f/packages/custom_lint/lib/src/workspace.dart#L116-L117 
    I've played around with the various methods in the Path package, and only `posix.prettyUri(sharedConstraint.path)` (`posix` is exposed by the path package) gave me a useful result. I'm not sufficiently familiar with Dart's Uri and with the Path Package to find a more elegant solution. Alternatively there's always the option to simply replace `\` with `/`, although I don't know how robust that is.

I'm happy to wrap the above into a PR, but would appreciate if someone can check my thinking first. Equally happy for you to implement a fix yourself:-)

**Comment by rrousselGit** [comment]
Those proposed fixes sound good. Feel free to make a PR!
