### ISSUE TITLE
Utilize `analysis_options` exclude

### ISSUE THREAD

**Issue by atoka93** [invertase/dart_custom_lint#25]
It would be useful to have the paths excluded in `analysis_options.yaml` also excluded in the custom lints.

I saw that the analyzer options are already available at `ContextRoot.optionsFile` so theoretically the exclude paths could be parsed and used, not sure if there is a better way to achieve that.

_A slightly lesser but possible solution to excluding would be #4._

**Comment by rrousselGit** [comment]
This should be fixed now
