### ISSUE TITLE
LintRule not running again on file change for non dart files

### ISSUE THREAD

**Issue by ishchhabra** [invertase/dart_custom_lint#252]
**Describe the bug**
When using `LintRule` (as opposed to `DartLintRule`) with an override for `filesToAnalyze`, the lint rules are not reloaded in VSCode, even when using `"dart.additionalAnalyzerFileExtensions"`

**To Reproduce**
1. Create a lint rule like 
```dart
class CustomLintRule extends LintRule {
  const CustomLintRule() : super(code: _code);

  static const _code = LintCode(
    errorSeverity: ErrorSeverity.ERROR,
    name: 'some-error',
    problemMessage: 'Error occured on {0}',
  );

  @override
  List<String> get filesToAnalyze => ['**.arb'];

  @override
  void run(
    CustomLintResolver resolver,
    ErrorReporter reporter,
    CustomLintContext context,
  ) {
    final timestamp = DateTime.now();
    reporter.reportErrorForSpan(
      _code,
      SourceSpan(SourceLocation(0), SourceLocation(0), ''),
      [timestamp.toIso8601String()],
    );
  }
}
```
and plugin like 

```dart
PluginBase createPlugin() => CustomPlugin();

class CustomPlugin extends PluginBase {
  @override
  List<LintRule> getLintRules(CustomLintConfigs configs) => [
        const CustomLintRule(),
      ];
}
```
2. Add `"dart.additionalAnalyzerFileExtensions": ["arb"]` to user settings in VSCode.
3. Create a `temp.arb` file and restart the analysis server. You'll notice an error on (0,0) with a timestamp
4. Modify the file. The timestamp will remain the same. 

**Expected behavior**
1. The `CustomLintRule.run` method should get called again and the error should update with a new timestamp.

**Comment by rrousselGit** [comment]
Thanks for the report.

I don't have time to debug this right now. Fancy looking into it?

**Comment by ishchhabra** [comment]
> Thanks for the report.
> 
> I don't have time to debug this right now. Fancy looking into it?

Sure. Any suggestions on where to start? If you might've a general idea of where the error could be, that might greatly help.

**Comment by rrousselGit** [comment]
One first step would be to check if `analyzeFile` in custom_lint_builder is re-executed when that file changes
https://github.com/invertase/dart_custom_lint/blob/c67d3527a215fdb06b95c2cc1b2c2633c9e55af7/packages/custom_lint_builder/lib/src/client.dart#L812C16-L812C27

**Comment by ishchhabra** [comment]
> One first step would be to check if `analyzeFile` in custom_lint_builder is re-executed when that file changes https://github.com/invertase/dart_custom_lint/blob/c67d3527a215fdb06b95c2cc1b2c2633c9e55af7/packages/custom_lint_builder/lib/src/client.dart#L812C16-L812C27

Looked into it. Neither `analyzeFiles` nor `analyzeFile` gets called for the changed file when modifying non-dart files (`arb` in the example above). I assume that means the issue is probably somewhere upstream of `custom_lint` (in `analyzer_plugin` perhaps). Is that correct?

**Comment by rrousselGit** [comment]
Quite possibly, yes. It could be that analyzer_plugin does not respect this setting.

Or maybe there's an issue with `filesToAnalyze` that custom_lint sends.

**Comment by ishchhabra** [comment]
> Quite possibly, yes. It could be that analyzer_plugin does not respect this setting.
> 
> Or maybe there's an issue with `filesToAnalyze` that custom_lint sends.

I looked into the analysis server and it has the following feature registration 

```json
  {
    "id": "24",
    "method": "textDocument/didChange",
    "registerOptions": {
      "documentSelector": [
        {
          "language": "dart",
          "scheme": "file"
        },
        {
          "language": "dart",
          "scheme": "dart-macro+file"
        },
        {
          "language": "yaml",
          "pattern": "**/pubspec.yaml",
          "scheme": "file"
        },
        {
          "language": "yaml",
          "pattern": "**/analysis_options.yaml",
          "scheme": "file"
        },
        {
          "language": "yaml",
          "pattern": "**/lib/{fix_data.yaml,fix_data/**.yaml}",
          "scheme": "file"
        }
      ],
      "syncKind": 2
    }
```

It looks like the language server does not seem to be registering the `additionalAnalyzerFileExtensions` that is being passed.  Do you know if there are any changes that need to be made in `custom_lint_plugin` to fix that, or is it just an error in the `analyzer_plugin`?

**Comment by ishchhabra** [comment]
UPDATE: I was able to hack a prototype to get it working with the following changes:
1. Adding `TextDocumentFilterWithScheme(scheme: 'file', pattern: '**/*.arb')` to https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/lsp/handlers/handler_text_document_changes.dart#L172-L178
2. In https://github.com/dart-lang/sdk/blob/main/pkg/analyzer_plugin/lib/plugin/plugin.dart#L86-L89, modifying `affected` to `affected..addAll(paths.where((path) => path.endsWith(".arb")))` (since `changeFile` does nothing when it is not a dart file)

Based on that, I think we can conclude that it is not an issue is not related to `custom_lint`

**Comment by ishchhabra** [comment]
> Awesome! Glad to hear you went all the way and found the issue.
> 
> Did you make an issue in the SDK repo?

Just created the issue and linked this issue there there so anyone who visits this can track that.

**Comment by ishchhabra** [comment]
@rrousselGit I was looking into it more. I think the issue is probably at https://github.com/invertase/dart_custom_lint/blob/main/packages/custom_lint/lib/src/v2/custom_lint_analyzer_plugin.dart#L324-L330. The `CustomLintServer` that is being used by `custom_lint` is responding back to the `analysis_server` with `*.dart`, which I missed earlier.

**Comment by rrousselGit** [comment]
> Since the patterns in custom_lint are defined in individual plugins, does the server have access to that information?

Not at that step.

We could send `*` though. Does this solve the issue?

**Comment by ishchhabra** [comment]
> > Since the patterns in custom_lint are defined in individual plugins, does the server have access to that information?
> 
> Not at that step.
> 
> We could send `*` though. Does this solve the issue?

I'll check that out soon. However, even if it works, couldn't it be a huge performance hit if the analyzer starts watching every file?

**Comment by ishchhabra** [comment]
> I'll check that out soon. However, even if it works, couldn't it be a huge performance hit if the analyzer starts watching every file?
@rrousselGit Yes, using `*` does seem to solve the issue. I'm not sure how big of a performance hit it would cause if we're watching on all open files though. If you think it should be fine, I'd be happy to create a PR (note: this would not solve the issue completely until the issue on `analysis_server` which i created above is also resolved).
