### ISSUE TITLE
Problem with report an element from another file

### ISSUE THREAD

**Issue by ivangalkindeveloper** [invertase/dart_custom_lint#253]
**Describe the bug**
Hello
Thank you very much for the package, it is a very convenient tool for analysis, although it needs to be studied well.

I'm trying to make a rule to check the keyword for BLoC events and states.
I thought that a class element provides a specific class declaration, but when reporting an error on a class element that may be located in another file, I get strange behavior - the error is highlighted in the analysis file of the block itself.
Or am I misunderstanding something about declaration elements?

**To Reproduce**
[Rule](https://github.com/ivangalkindeveloper/pedant/blob/master/lib/src/rule/add/add_bloc_event_sealed_rule.dart):
```
class AddBlocEventSealedRule extends DartLintRule {
  const AddBlocEventSealedRule({
    required this.priority,
  }) : super(
          code: const LintCode(
            name: "add_bloc_event_sealed",
            problemMessage: "Add BLoC Event class sealed keyword",
            correctionMessage:
                "Please add 'sealed' keyword base Event class of this BLoC.",
            errorSeverity: ErrorSeverity.ERROR,
          ),
        );

  final int priority;

  @override
  void run(
    CustomLintResolver resolver,
    ErrorReporter reporter,
    CustomLintContext context,
  ) =>
      context.registry.addClassDeclaration(
        (
          ClassDeclaration node,
        ) {
          final ClassElement? blocElement = node.declaredElement;
          if (blocElement == null) {
            return;
          }

          if (blocTypeChecker.isAssignableFrom(
                blocElement,
              ) ==
              false) {
            return;
          }

          final InterfaceType? supertype = blocElement.supertype;
          if (supertype == null) {
            return;
          }

          final List<DartType> typeArguments = supertype.typeArguments;
          if (typeArguments.length != 2) {
            return;
          }

          final DartType eventType = typeArguments.first;
          if (eventType.element is! ClassElement) {
            return;
          }

          final ClassElement eventElement = eventType.element as ClassElement;
          final String blocPackagePath =
              blocElement.source.fullName.split("lib").first;
          final String eventPackagePath =
              eventElement.source.fullName.split("lib").first;
          if (blocPackagePath != eventPackagePath) {
            return;
          }
          if (eventElement.isSealed == true) {
            return;
          }

          reporter.atElement(
            eventElement,
            this.code,
          );
        },
      );
}
```

Example - [Bloc](https://github.com/ivangalkindeveloper/pedant/blob/master/example/lib/add/add_bloc_event_sealed.dart) and [Event](https://github.com/ivangalkindeveloper/pedant/blob/master/example/lib/add/add_bloc_event_sealed_event.dart).

The `eventElement.source` property of the element under study shows correctly - `.../pedant/example/lib/add/add_bloc_event_sealed_event.dart`

Reporting problem:
![Снимок экрана 2024-06-09 в 02 30 45](https://github.com/invertase/dart_custom_lint/assets/78663629/8f69adec-8a3d-44ac-bce3-73882e2ce696)

**Expected behavior**
Error highlighting in another file.

**Comment by rrousselGit** [comment]
Diagnostics can only be emitted on the file your lint is running against. There's no such thing as "analyze file A, but emit a warning on file B".

If you want to emit a warning on a file, the analyzed file should be that file.

You'll therefore need to either:
- Refactor your lint to rely on information from the `add_bloc_event_sealed_event.dart` file only.
  This could be done by relying on the file name or a custom annotation to help the linter know more about the class.
- change the location of the warning to be inside `add_bloc_event_sealed.dart` instead.
  For example a good candidate is to warn on the `BlocEvent` as part of `Bloc<BlocEvent, String>`

In any cases, that's expected.
