### ISSUE TITLE
custom_lint doesn't provide VM service URI for debugging

### ISSUE THREAD

**Issue by BuyMyBeard** [invertase/dart_custom_lint#255]
**Describe the bug**
When running `dart run custom-lint --watch` in terminal or looking in custom_lint.log, no VM service Uri is to be found to attach the Dart process of the custom_lint package.

![image](https://github.com/invertase/dart_custom_lint/assets/95039323/cf1a1ac8-146e-4995-9afa-38938d537b1f)

Even though custom_lint in analysis_options.yaml is set to `debug: true` and `verbose: true`, only errors are outputted into the custom_lint.log file.

**To Reproduce**
I tried setting up my own custom_lint package and another dart project depending

Here, I have added a sample project used to reproduce the issue. it depends on pyramid_lint, a custom_lint package that should be debuggable.
[sample.zip](https://github.com/user-attachments/files/15919636/sample.zip)

**Expected behavior**
![image](https://github.com/invertase/dart_custom_lint/assets/95039323/979d0c94-e757-4bb6-9dcd-8f27f5bcec90)

**Comment by rrousselGit** [comment]
Should be fixed in 0.6.5
