### ISSUE TITLE
`LintCode` class conflicts with `LintCode` from `analyzer`

### ISSUE THREAD

**Issue by Rexios80** [invertase/dart_custom_lint#261]
**Describe the bug**
```console
The name 'LintCode' is defined in the libraries 'package:analyzer/src/dart/error/lint_codes.dart (via package:analyzer/error/error.dart)' and 'package:custom_lint_core/src/lint_codes.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.dart[ambiguous_import](https://dart.dev/diagnostics/ambiguous_import)
```

It looks like `LintCode` got exported in `analyzer: 6.8.0`. Should we switch to using it instead of the object owned by `custom_lint`?

**To Reproduce**

1. Be on Flutter master or any other version of Dart/Flutter that supports `analyzer: 6.8.0`
2. Attempt to use a `custom_lint`

**Expected behavior**
No conflicts

**Comment by Rexios80** [comment]
This might not be the only issue with using `custom_lint` with Flutter channel master

**Comment by rrousselGit** [comment]
There are lots of issues with the master channel unfortunately. I'm working on all of those already

**Comment by Rexios80** [comment]
Welp this started causing analysis issues on pub.dev: https://pub.dev/packages/firebase_rules_linter

Is there anything I can do to help here?

**Comment by rrousselGit** [comment]
For plugins, you can use `import ... as prefix` or `import ... hide LintCode, ...`, and publish a new version with those.

As for how broken custom_lint currently is, unfortunately you can only wait until I fix it. It's effectively a rewrite, so it's taking time.

**Comment by rrousselGit** [comment]
Overriding analyzer to >=6.0.0<6.6.0 should be relatively fine for now. I'm working on a fix, but it's challenging

**Comment by brilliapps** [comment]
Sorry, i am not sure if i understand (still not experienced). Could possibly custom_lint work out of the box with dart 3.5 (it doesn't) if i changed the analyzer version? I have 3.4.4 and actually need also the 3.5 version of macros (need both), but custom_lint is NOW more important and the macros can wait a little longer.

**Comment by rrousselGit** [comment]
Well I'm working on it.

**Comment by brilliapps** [comment]
Yeah, i already knew this and asked recently in a separate issue and got answered. I didn't mean my request here to be rude because it looks like i am impatient. The question was if having dart 3.5 and the newest custom_lint from pub.dev (0.6.4) downgrading analyser only to some newer version would cause custom_lint start to work, although maybe even not fully well (3.5 has improved macros to the 3.4 dart version). So please, this post here is more to explain myself not to bother you and get answer :)

**Comment by rrousselGit** [comment]
Fixed in 0.6.5

**Comment by provokateurin** [comment]
Awesome!! Will try it out right away

**Comment by provokateurin** [comment]
Works as expected, thank you so much :)

**Comment by Rexios80** [comment]
Works great! Thanks @rrousselGit!
