### ISSUE TITLE
Update  rxdart 0.28.0

### ISSUE THREAD

**Issue by victorcode1** [invertase/dart_custom_lint#262]
[invuKDS] flutter pub get --no-example
Resolving dependencies...
Because custom_lint 0.6.4 depends on rxdart ^0.27.7 and invukds depends on rxdart 0.28.0, custom_lint 0.6.4 is forbidden.
So, because invukds depends on custom_lint 0.6.4, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on rxdart: flutter pub add rxdart:^0.27.7

**Comment by rrousselGit** [comment]
That's a duplicate
