### ISSUE TITLE
Medhod call: Adding in-context evaluation of literals, constants (pointer, expressions or variables of computable values)

### ISSUE THREAD

**Issue by brilliapps** [invertase/dart_custom_lint#265]
It took me much time to figure out that my request is valid.
When we have
context.registry.addMethodInvocation((inv) …)
the only way one can get to the value of the method argument is this:
inv.argumentList.arguments.first.unParenthesized;
But as far as i understand it cannot be computed in context where it was passed to the method.
for this an argument would have to return element like first.element, and then the value - if a literal or constant (or even variables which values can be computed during analysis) it could be computed like this:
computeConstantValue()
This would return a Dart Object and could be used and compared with something

So my question is can i compute the argument or may i request for the corresponding feature computing argument value?

**Comment by brilliapps** [comment]
As my knowledge of analyzer grows i can see that the Expression of f.e. inv.argumentList.arguments.first can be also DoubleLiteral (double .value), or reliable SimpleStringLiteral (Strint .stringValue), and more. Also while couldn't figure out how to use Lists this way or if i can compare two lists with ==, but if the Expression is Identifier and VariableElement of const (!) variable then .computeConstantValue() can be used and a List can be created via .toListValue(). Also for a even complicated custom class SomeClass instance created via .computeConstantValue() i can compare two different instances correctly with == - it works as i was afraid it wouldn't, but it does. So what is possible is much more than i expected and it is sufficient for now.
But it is true that:
1. As far as i understand still such a call someMethod(const [1, 2]) can't be computed - the issue so could stay here (you might decide if it should be closed)?. And also.
2. non-const variables that current value that yet #could# be statically computed can't  be used.
3. Most probably it is analyzer feature request not custom_lint as i am able more and more to distinguish what is what.

**Comment by rrousselGit** [comment]
It's definitely more an analyzer feature than a custom_lint one. I don't think custom_lint can realistically add new features here.
