### ISSUE TITLE
Error: 'NullAwareElement' isn't a type.

### ISSUE THREAD

**Issue by jayveecaayao** [invertase/dart_custom_lint#282]
**Describe the bug**
Since 0.6.9, this error appears when I run build_runner.

I tried downgrading to 0.6.5, and this issue disappeared. Seems to only be an issue with 0.6.9? Thanks!

```[INFO] Precompiling build script......
[WARNING] ../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.9/lib/src/node_lint_visitor.g.dart:818:30: Error: Type 'NullAwareElement' not found.
  void visitNullAwareElement(NullAwareElement node) {
                             ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.9/lib/src/node_lint_visitor.g.dart:2160:28: Error: Type 'NullAwareElement' not found.
  final List<_Subscription<NullAwareElement>> _forNullAwareElement = [];
                           ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.9/lib/src/node_lint_visitor.g.dart:2162:33: Error: Type 'NullAwareElement' not found.
      String key, void Function(NullAwareElement node) listener) {
                                ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.9/lib/src/node_lint_visitor.g.dart:3365:42: Error: Type 'NullAwareElement' not found.
  void addNullAwareElement(void Function(NullAwareElement node) listener) {
                                         ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.9/lib/src/node_lint_visitor.g.dart:818:30: Error: 'NullAwareElement' isn't a type.
  void visitNullAwareElement(NullAwareElement node) {
                             ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.9/lib/src/node_lint_visitor.g.dart:820:11: Error: Superclass has no method named 'visitNullAwareElement'.
    super.visitNullAwareElement(node);
          ^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.9/lib/src/node_lint_visitor.g.dart:2160:28: Error: 'NullAwareElement' isn't a type.
  final List<_Subscription<NullAwareElement>> _forNullAwareElement = [];
                           ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.9/lib/src/node_lint_visitor.g.dart:2162:33: Error: 'NullAwareElement' isn't a type.
      String key, void Function(NullAwareElement node) listener) {
                                ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.9/lib/src/node_lint_visitor.g.dart:3365:42: Error: 'NullAwareElement' isn't a type.
  void addNullAwareElement(void Function(NullAwareElement node) listener) {
                                         ^^^^^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 3.2s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.```

**Comment by rrousselGit** [comment]
Dang it, I forgot to bump the minimum analyzer to 6.10.0

Give me a second

**Comment by rrousselGit** [comment]
Actually, custom-lint-core does require analyzer 6.10.0 already

What analyzer version did you download locally? You can look at your `/.dart_tool/package_config.json` to know

**Comment by mdddj** [comment]
``` 
dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.3
  copy_with_extension_gen: ^5.0.4
  isar_generator: ^3.1.0+1
  analyzer: ^6.9.0


dependency_overrides:
  analyzer: ">=6.8.0 <6.12.0"
  web: any
  flutter_lints: ^5.0.0
  collection: "1.19.0"
```
 the same problem
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/1f5ab75c-237e-47a2-a5eb-20b246624e30">

**Comment by mdddj** [comment]
temporary solution

```yaml
dependency_overrides:
  custom_lint_core: 0.6.5
```

**Comment by rrousselGit** [comment]
Your dependency_override could be the issue here.

custom_lint 0.6.9 and above requires analyzer 6.10.0.

**Comment by mdddj** [comment]
I have tried this plan, but I got an error
```dart
Because analyzer >=6.9.0 depends on macros >=0.1.3-main.0 <0.1.4 which depends on _macros 0.3.3 from sdk, analyzer >=6.9.0 requires _macros 0.3.3 from sdk.
So, because no versions of _macros from sdk match 0.3.3 and erp_system depends on analyzer >=6.10.0 <6.12.0, version solving failed.
```
flutter `3.24.3`
<img width="277" alt="image" src="https://github.com/user-attachments/assets/9646ef1d-b16d-426d-a94c-f9dd798bee61">
<img width="1285" alt="image" src="https://github.com/user-attachments/assets/cd1a1c26-76c6-47d9-8841-ae7b9f21f686">

**Comment by rrousselGit** [comment]
You may have to upgrade your Dart SDK (and use Flutter's master channel if necessary).
custom_lint is using the latest analyzer. From there's it's about making sure your _other_ packages use the latest analyzer too.

**Comment by jayveecaayao** [comment]
Ohh I see. We're currently on `analyzer: "6.7.0"`, so maybe that's the issue. Some of our packages are still outdated. Thank you for the response :D

**Comment by PeterStaev** [comment]
For anyone experiencing this problem you have to downgrade custom_lint to a fixed version 0.6.7 or lower AND also have a dependency override for custom_lint_core to 0.6.5

@rrousselGit may be not such a good idea to push versions that are depending on bleeding edge versions of flutter/dart as a minor version upgrades, since most users use `^` for version spec and they might unknowingly pull a version that is not compatible with the stable flutter channel (which is probably mostly used for all production apps). 
Also might be a good idea to bump the analyzer version in the pubspec of the package, in order to indicate that the version they are using is not compatible with the old analyzer. Right now it is set as `^6.6.0` yet, the package is using features from `6.10.0`

**Comment by rrousselGit** [comment]
The analyzer version is already bumped.

custom_lint doesn't use 6.10.0
custom_lint_core does, and it does use the correct version.

> may be not such a good idea to push versions that are depending on bleeding edge versions of flutter/dart as a minor version upgrades

That's not custom_lint's issue. That's pub's issue.

The problem isn't `^`. It's that given a package with version `6.1.1`, folks install it as `^6.1.1` instead of `^6.0.0`.
That's because that's how `pub add` and the copy-paste from `pub.dev` defaults.

**Comment by rrousselGit** [comment]
But it looks like the tight constraint on `custom_lint_core` was inadvertently changed to use `custom_lint_core: ^...`

That's a problem. I'll revert that.
