### ISSUE TITLE
Broken on Flutter 3.27 beta

### ISSUE THREAD

**Issue by Rexios80** [invertase/dart_custom_lint#284]
**Describe the bug**
The linter does not appear to run at all. No log file is created.

**To Reproduce**
Be on flutter 3.27.0-0.1.pre

**Expected behavior**
The linter runs

**Comment by rrousselGit** [comment]
It work on both stable and master channel for me.
Do you have any special way to reproduce?

**Comment by Rexios80** [comment]
I used fvm to switch to the beta channel and then it stopped running. Unfortunately I don't have any more details since it seems like the plugin is crashing before it starts logging. Maybe master fixed it?

**Comment by rrousselGit** [comment]
I don't use fmv.
Fmv could be the issue.

**Comment by Rexios80** [comment]
Not sure what the issue was but it seems to work now
