### ISSUE TITLE
Issues in the finding Flutter widgets

### ISSUE THREAD

**Issue by singlesoup** [invertase/dart_custom_lint#42]
Hello, I am using Custom_lint Package. To write some project specific lints. Like I want my team to use a project specific CustomScaffold rather flutter given Scaffold. 

But since this is build on top on Dart Analyzer, which has no way of identifying Flutter Widgets, how can we detect Flutter Widgets with this ?

Tried both Element Tree as well as AST, but since in the documentation there was no mention of Flutter widget, it didn't help much. So it would be amazing if you guys could find some time to see how can we detect Flutter widgets with this.

**Comment by rrousselGit** [comment]
You'll want to visit the AST of the `build` function. From there, search for an `ast is InstanceCreation` AST (or something with a similar class name, can't remember exactly which one)

With that done, you can obtain the Element. Doing `element is ClassElement` will give you info about the class instantiated

**Comment by singlesoup** [comment]
I have tried obataining _Element_ from `InstanceCreationExpression` by visiting  _Build_ Class Members, as you mentioned. But was not able to find any. Element Would it be possible for you point me to the direction where I can get Element from Instrance Creation?

**Comment by rrousselGit** [comment]
There's `InstanceCreationExpression.staticType`  which is a DartType. And you can access an Element from with with `.element`

**Comment by singlesoup** [comment]
Its coming as Null, as its nullable and it won't return staticType utill AST is resolved. How do we make sure its not null, can we await it? 
Or Should I use Future.Delayed with '0' seconds?

![image](https://user-images.githubusercontent.com/54581715/203317356-297c73c8-380e-4a11-8783-f913f3dc95c3.png)

**Comment by singlesoup** [comment]
hey thanks @rrousselGit , was able to solve the issue.
