### ISSUE TITLE
No UI Feedback in Android Studio

### ISSUE THREAD

**Issue by AdamNSmith** [invertase/dart_custom_lint#47]
**Describe the bug**
With the latest update to dart_custom_lint (0.0.13), the linter works from the command line but doesn't work in Android Studio. 

**To Reproduce**
Use dart_custom_lint version 0.0.13, create a custom lint, write code that violates the custom lint rule, and then notice that the violation is not reported in the Android Studio IDE.

**Expected behavior**
Violations of custom lint rules are displayed when running dart_custom_lint from both the command line and the Android Studio IDE.

**Comment by rrousselGit** [comment]
Rolf, the tools/analyzer_plugin broke again.
Will fix

**Comment by rrousselGit** [comment]
Try again with the 0.0.14

It's unfortunately not something I can test without publishing a package, as it's an issue which happens only when the package is published :shrug:

**Comment by AdamNSmith** [comment]
0.0.14 fixed it. Thanks for the quick response and fix. 👍
