### ISSUE TITLE
Allow applying quick fixes with a command

### ISSUE THREAD

**Issue by Clavum** [invertase/dart_custom_lint#57]
Would it be possible for the Quick Fixes for our custom lints to be run with either `dart fix` or a custom command like `dart run custom_lint fix`?

**Comment by rrousselGit** [comment]
Sounds reasonable.

**Comment by rrousselGit** [comment]
Since you appear to be quite familiar with the SDK, are you aware of how they handle bulk fixes?

Applying all fixes in sequential sounds very inefficient. But I'm currently unaware of an easy way to merge multiple fixes to execute them at once.
Any idea?

**Comment by Clavum** [comment]
Oh, it's just a superficial knowledge from reading some code when I was trying to understand how their lints were structured.

This seems to be folder for anything Fix related:
https://github.com/dart-lang/sdk/tree/main/pkg/analysis_server/lib/src/services/correction
And this seems like the class most related to bulk fixes, but doesn't look too helpful for us:
https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/correction/bulk_fix_processor.dart

I suppose my hope was the fixes could be supplied to the SDK in some way (through the analyzer_plugin) so that it handles them the same way it does its own.

Because, yeah, otherwise it would get rather complicated managing applying multiple fixes at the same time, especially when applying fixes created by plugin users that could possibly create additional lints in the code when run, or never get tested in bulk, etc. How the SDK does it, I do not know; do they keep applying fixes in waves until there are no more analysis issues?

It might not be feasible.

My hope was to soon use custom lints for my job. We have a half million line codebase, so applying fixes with a command would be nice, but probably not worth a huge effort to make possible.

**Comment by rrousselGit** [comment]
> Oh, it's just a superficial knowledge from reading some code when I was trying to understand how their lints were structured.

That's still more than most people :)

Anyway, I had the same feeling. Maybe there's something I missed so I'll look more into it later. But for now, it might be a bit complex.

**Comment by esuljic** [comment]
Any update?

**Comment by rrousselGit** [comment]
I suppose for now it might be worth it to implement a `while (hasLintsWithQuickFixes) applyFirstQuickFix()`

There's a lot of value in such fix. So even if slow at first, that's better than nothing. `dart fix` isn't exactly super fast anyway

**Comment by rrousselGit** [comment]
Closing in favor of https://github.com/invertase/dart_custom_lint/issues/161

I'll try to implement this in the following weeks.
