### ISSUE TITLE
Incorrect documentation for how to use hot restart/reload

### ISSUE THREAD

**Issue by iLoveDocs** [invertase/dart_custom_lint#59]
[Docs say](https://pub.dev/packages/custom_lint#using-the-dart-debugger-and-enabling-hot-restart): 

> First, create a tools/custom_lint_debug.dart file next to tools/custom_lint.dart with the following content:

```dart
import 'dart:io';
import 'package:custom_lint/basic_runner.dart';

void main() {
  await customLint(workingDirectory: Directory.current.parent);
}
```

We never created a `tools/custom_lint.dart` file but a `bin/custom_lint.dart` file, so where the former came from? 

Once I created a `tools/custom_lint_debug.dart` file (without having a tools/custom_lint.dart file), after running it (or should I not run it?), I get the following error: 

> Bad state: No pubspec.yaml found at /Users/me/flutter/packages/flutter/.

2nd issue. The code is also missing an `async`. 

```
void main () async { ...} // added async
```

**Comment by rrousselGit** [comment]
That was correct because the mechanism was a bit weird.

But there's a different mechanism now and the docs have been updated.
