### ISSUE TITLE
[Feature request] Project path

### ISSUE THREAD

**Issue by smsimone** [invertase/dart_custom_lint#65]
I'm currently working on a custom lint which works with my library for strings localization and I have a file containing all the available keys so the user will be notified on the debug console if he's using an invalid keyword.

It would be nice to have something to fetch the project directory so it would be possible to read local files on the plugin initialization like:

```dart
PluginBase createPlugin() => _CustomPlugin();

class _CustomPlugin extends PluginBase {
  _CustomPlugin() {
    final file = File('$projectDir/filename');
  }
}
```

**Comment by rrousselGit** [comment]
Could you expand on the problem? I am not following. What's lacking with the current system, and how would you like this to be solved?

**Comment by smsimone** [comment]
Currently I have to generate a `json` file which contains all the available keys for localization and I'm writing a linter which validate the keys inserted in widget against those.

The file is generated in the root folder of the project but because of the linter being run in another location, I cannot retrieve the project directory directly in the `createPlugin()` callback, but I have to call this method during the analysis of the first file:

```dart
Uri _containsKeyFile(Uri uri) {
    try {
      if (uri.pathSegments.length == 1) {
        throw Exception('Failed to find keys file, have you generated it?');
      }

      final dirPath = p.dirname(uri.path);
      final dir = Directory.fromUri(Uri.parse(dirPath));
      if (dir.existsSync()) {
        final files = dir.listSync();
        final isContained = files.any((t) => t.path.contains(keysFilename));
        if (!isContained) return _containsKeyFile(dir.uri);
        return dir.uri;
      }
      throw Exception('dir $uri does not exists');
    } catch (e) {
      log(
        'Failed to find keys file',
        error: e,
        name: 'flutter_ditto',
      );
      return uri;
    }
  }

```

If it's possible, it would be much better to have a single callback or property inside `PluginBase` to access the path of the project

**Comment by rrousselGit** [comment]
The path of the project is unavailable there. At that point in time, custom_lint has no clue yet what the projects are

**Comment by rrousselGit** [comment]
Closing as there is no plan to do such a thing
