### ISSUE TITLE
Leftover client processes

### ISSUE THREAD

**Issue by kuhnroyal** [invertase/dart_custom_lint#71]
**Describe the bug**
`custom_lint` client processes are not being shut down.
This is on version `0.2.0`.

<img width="626" alt="Bildschirm­foto 2023-01-31 um 12 10 34" src="https://user-images.githubusercontent.com/1260818/215744564-b059d5ec-7660-4bca-a6ee-ee10608ea858.png">

**To Reproduce**
Every time the analysis server restarts, there are 2 new left over processes:
1x `dart:custom_lint_client.dart`
1x `dart:dds.dart.snapshot`

In the screenshot I was able to reproduce this by just pressing `Restart Analysis Server` in IntelliJ.

**Expected behavior**
The processes should be shut down when the client is shut down.

**Comment by kuhnroyal** [comment]
I also noticed that running `dart run custom_lint` hangs and never ends when there are errors. May be this is related.

**Comment by rrousselGit** [comment]
Yeah Yeah I'm aware of this. I'm not sure how to debug  this though

**Comment by Ehesp** [comment]
I have no idea if this is related, but for visibility, when working on [dart_edge](https://github.com/invertase/dart_edge) child processes would simply not be killed as long as a file watcher was alive.

At first, I thought it was a `hotreloader` issue, however after switching to use the `watcher` package, the issue persisted. The only way I could successfully kill a child process and perform file watching, was to kill the watcher, then kill the process, and restart the watcher.

This is the code: https://github.com/invertase/dart_edge/blob/main/packages/edge/lib/src/dev_server.dart#L53-L90

I didn't investigate as to why this was happening, but it was the only workaround we could find.

**Comment by rrousselGit** [comment]
Found a solution. Apparently analyzer_plugin never sends the "plugin shutdown" event. And my safeguard wasn't working

I fixed the safeguard, so all's good now.

**Comment by kuhnroyal** [comment]
Looks good, can confirm that I no longer have the problem.
Thanks!
