### ISSUE TITLE
Enforcing dart documentation

### ISSUE THREAD

**Issue by literalEval** [invertase/dart_custom_lint#75]
I wanted to ask if it is possible to create a linter rule that enforces dart documentation ? Like it checks if the class, its methods and attributes are properly documented and follow dart doc guidelines. 
Does any rule like this already exist ? If no, then can you please hint me in the right direction so that I can create one ?

**Comment by rrousselGit** [comment]
There's https://dart.dev/tools/linter-rules#package_api_docs

You can implement something with custom_lint too. But that's too broad of a question
