### ISSUE TITLE
Command line throws if the current project does not contain custom_lint plugins

### ISSUE THREAD

**Issue by rrousselGit** [invertase/dart_custom_lint#77]
Currently, running `custom_lint` in a project which does not contain any custom_lint plugin causes the command line to fail.

It should instead run successfully, with maybe a warning message

**Comment by literalEval** [comment]
I would like to fix this issue @rrousselGit

**Comment by rrousselGit** [comment]
Sure, give it a go

**Comment by literalEval** [comment]
@rrousselGit Can you please look at PR #82 and merge it ?

**Comment by literalEval** [comment]
Thanks a lot @rrousselGit . You're awesome :)
