### ISSUE TITLE
Bad state: Two ContextRoots Error with Sub Packages

### ISSUE THREAD

**Issue by getBoolean** [invertase/dart_custom_lint#79]
**Describe the bug**
I am trying to use `riverpod_lint`, but I get this error when I run `dart run custom_lint`. This happens when I am using melos with a packages directory. I have reproduced it without using melos.

```log
The request analysis.setContextRoots failed with the following error:
RequestErrorCode.PLUGIN_ERROR
Bad state: Two ContextRoots depend on _fe_analyzer_shared but use different version,
therefore custom_lint does not know which one to pick.
- file:///Users/boolean/.pub-cache/hosted/pub.dev/_fe_analyzer_shared-53.0.0/
- file:///Users/boolean/.pub-cache/hosted/pub.dev/_fe_analyzer_shared-52.0.0/

at:
#0      _writePackageConfigForTempProject (package:custom_lint/src/v2/server_to_client_channel.dart:96:9)
#1      _SocketCustomLintServerToClientChannel.init (package:custom_lint/src/v2/server_to_client_channel.dart:255:5)
#2      CustomLintServer._maybeSpawnCustomLintPlugin (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:289:25)
<asynchronous suspension>
#3      CustomLintServer._handleAnalysisSetContextRoots.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:264:9)
<asynchronous suspension>
#4      PendingOperation.run (package:custom_lint/src/async_operation.dart:14:14)
<asynchronous suspension>
#5      CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:124:22)
<asynchronous suspension>
```

**To Reproduce**

[I have reproduced it in a separate flutter project without melos](https://github.com/getBoolean/custom_lint_test). A dart subpackage `models` is a dependency of the app. The command works if I delete the `packages` folder (and remove the `models` dependency).

1. Clone repo
2. `flutter pub get`
3. `cd packages/models`
4. `dart pub get`
5. `cd ../..`
6. `dart run custom_lint` (see above output)

**Expected behavior**
`dart run custom_lint` should output that ProviderScope should be used

**Comment by getBoolean** [comment]
Possibly related but with different error output: https://github.com/invertase/dart_custom_lint/issues/40

**Comment by rrousselGit** [comment]
This is expected. You need to solve the version issue, such that all packages in your repo use the same _fe_analyzer_shared version

**Comment by getBoolean** [comment]
> This is expected. You need to solve the version issue, such that all packages in your repo use the same _fe_analyzer_shared version

This happens when both `flutter_test` and `test` are used. Is there a fix other than requiring all sub-packages to be flutter packages if they are to be tested?

**Comment by getBoolean** [comment]
Since any flutter package that uses `custom_lint` cannot have a dart package under its `packages` directory, I've found a workaround.

For Flutter projects, make the app a Flutter package in the `packages` folder, and have a dummy `lib/main.dart` which just calls the `main.dart` from the `app` package. The dummy `main.dart` is so that the normal flutter commands work. (This is easier to manage using `melos`)

Example file structure:

```
flutter_proj/
  - lib/main.dart
  - packages/app/lib/
      - main.dart
      - app.dart

```

```yaml
# melos.yaml
packages:
  - packages/*
  - "./"
```

Using this structure, the app package can use `custom_lint`. I'm sure there is an alternative solution without moving the app into its own package.

**Comment by literalEval** [comment]
@getBoolean had the same issue. The thing is that `flutter pub get` downloads the latest possible versions of dependencies required in your `<your_custom_lint>` package. But when you run `flutter pub get` in your actual project, it sees that `<your_custom_lint>` depends on newer version of packages but `<your_project>` needs some lower version of the same dependencies. 

The workaround I came up with is adding `custom_lint_builder`, `analyzer` and `analyzer_plugin` (basically all of your `<your_custom_lint>` package dependencies) in `<your_project>`'s `pubspec.yaml`. Run `flutter_pub_get` again. If the issue persists, manually add old versions of conflicting packages to `<your_custom_pugin>`'s `pubspec.yaml`.

Hope this helps someone new.

**Comment by rrousselGit** [comment]
> This happens when both flutter_test and test from sdk are used. Is there a fix other than requiring all sub-packages to be flutter packages if they are to be tested?

You need to use a specific version.

Make sure all your projects support the latest version possible of those dependencies and run `pub upgrade` everywhere.

**Comment by rrousselGit** [comment]
Closing as this is expected.
There is a separate issue for tracking improvements to the error message
