### ISSUE TITLE
Asynchronous lints

### ISSUE THREAD

**Issue by abitofevrything** [invertase/dart_custom_lint#81]
**Is your feature request related to a problem? Please describe.**
It would be nice to allow for asynchronous lint rules and/or post run callbacks. Some of the methods from the analyzer return a future (in my case [`AnalysisSession.getResolvedLibraryByElement`](https://pub.dev/documentation/analyzer/latest/dart_analysis_session/AnalysisSession/getResolvedLibraryByElement.html)) and currently the best (and only) way to handle these is to use `waitFor` from `dart:cli` which is deprecated and not something a published package should rely on.

**Describe the solution you'd like**
Update most linter/callback APIs to take `FutureOr<void>` instead of `void` as the return types of functions.

**Describe alternatives you've considered**
`waitFor` could be used, but it isn't great as mentioned above. We could also of course use `analyzer_plugin` directly and forego this package but this isn't such a complex task that we need this.

**Additional context**
I am willing to put forward a PR for this as I will be trying to implement it for my own use in my own fork anyway.

**Comment by rrousselGit** [comment]
The solution is to instead await everything you need inside `setup`, like what `DartLintRule` does

**Comment by rrousselGit** [comment]
Making those functions async has many challenges, as it'll most likely break things like `context.registry`

**Comment by abitofevrything** [comment]
That's why I mentioned post run callbacks being async as well, as that is what `context.registry` relies on.

I didn't spot that we could await this in `setup` though. Might be a good idea to throw a line in the docs about that use case, but I guess this issue exists now for others that might run into this problem.

**Comment by rrousselGit** [comment]
Post run callbacks being async isn't enough for context.registry

The issue is that AstVisitors hardly can be async (at least not without a large cost). So even if postRunCallbacks were async, the lint would still have to execute synchronously
