### ISSUE TITLE
migrate json_serializable to dev_dependencies

### ISSUE THREAD

**Issue by yamarkz** [invertase/dart_custom_lint#99]
Thank you for the great package.
We make a lot of custom lint and are supported by development.

What is the purpose of importing json_serializable in dependencies?
Do you plan to move to dev_dependencies?

We are making extended use of json_serializable, which is causing a compatibility in the custom_lint import source.

~I could not see any code using json_serializable, I would like to know the intent of importing.~
I understand that it is used in the development of v2.

https://github.com/invertase/dart_custom_lint/blob/main/packages/custom_lint/lib/src/v2/protocol.g.dart

https://github.com/invertase/dart_custom_lint/blob/59ccd890d0e7e34fa4814b77d133ac6a191acaaf/packages/custom_lint/pubspec.yaml#L19

**Comment by rrousselGit** [comment]
fixed by b44e3d4ac8b04e818cf755dfe63e14bc61de32ee
